package com.tanquandan.blogsystem.mapper;

import com.tanquandan.blogsystem.DAO.Tag;
import com.tanquandan.blogsystem.DAO.TagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Mon May 29 09:01:00 CST 2023
     */
    long countByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Mon May 29 09:01:00 CST 2023
     */
    int deleteByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Mon May 29 09:01:00 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Mon May 29 09:01:00 CST 2023
     */
    int insert(Tag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Mon May 29 09:01:00 CST 2023
     */
    int insertSelective(Tag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Mon May 29 09:01:00 CST 2023
     */
    List<Tag> selectByExampleWithRowbounds(TagExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Mon May 29 09:01:00 CST 2023
     */
    List<Tag> selectByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Mon May 29 09:01:00 CST 2023
     */
    Tag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Mon May 29 09:01:00 CST 2023
     */
    int updateByExampleSelective(@Param("row") Tag row, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Mon May 29 09:01:00 CST 2023
     */
    int updateByExample(@Param("row") Tag row, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Mon May 29 09:01:00 CST 2023
     */
    int updateByPrimaryKeySelective(Tag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Mon May 29 09:01:00 CST 2023
     */
    int updateByPrimaryKey(Tag row);
}